// Generated by CoffeeScript 1.8.0
var Hapi, client, server;

Hapi = require('hapi');

server = new Hapi.Server();

server.connection({
  port: process.env.PORT || 5000
});

client = require('redis').createClient(process.env.REDIS_URL);


/*
REGISTER VIEWS
 */

server.views({
  engines: {
    jade: require('jade')
  },
  relativeTo: __dirname,
  path: './views',
  layoutPath: './views/shared',
  isCached: false
});


/*
ROUTES
 */

server.route({
  method: 'GET',
  path: '/favicon.ico',
  handler: function(request, reply) {
    return reply.file("./favicon.ico");
  }
});

server.route({
  method: 'GET',
  path: '/images/{file*}',
  handler: {
    directory: {
      path: 'public/images',
      listing: true
    }
  }
});

server.route({
  method: 'GET',
  path: '/css/{file*}',
  handler: {
    directory: {
      path: 'public/css',
      listing: true
    }
  }
});

server.route({
  method: 'GET',
  path: '/scripts/{file*}',
  handler: {
    directory: {
      path: 'public/scripts',
      listing: true
    }
  }
});

server.route({
  method: 'GET',
  path: '/{file*}',
  handler: {
    directory: {
      path: 'public',
      listing: true
    }
  }
});

server.route({
  method: 'GET',
  path: '/',
  handler: {
    view: 'index'
  }
});

server.route({
  method: '*',
  path: '/{anything*}',
  handler: function(request, reply) {
    return reply.redirect("/");
  }
});

server.start(function() {
  return console.log("Server running on " + server.info.uri);
});
